networks:
    backend:
        driver: bridge

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx:/etc/nginx/conf.d
        ports:
            - 8080:80
        depends_on:
            - php
            - mysql
        networks:
            - backend

    mysql:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        volumes:
            - ./.docker/.mysql:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=password
        networks:
            - backend

    php:
        build:
            context: ./.docker
            dockerfile: Dockerfile.php
        image: php-image
        container_name: php
        volumes:
            - ./:/var/www/html
        ports:
            - 9000:9000
        networks:
            - backend